name: Daily Commit Workflow

on:
  schedule:
    # Runs at 08:00 UTC every day (you can adjust the time)
    - cron: "0 8 * * *"
  workflow_dispatch: # Allows manual triggering

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add file with email 24f3002795@ds.study.iitm.ac.in
        run: |
          echo "This is an automated daily commit by 24f3002795@ds.study.iitm.ac.in" > daily-commit.txt

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add daily-commit.txt
          git commit -m "Daily automated commit by 24f3002795@ds.study.iitm.ac.in [skip ci]" || exit 0
          git push
